services:
  web:
    image: registry.registry.svc.cluster.local:5000/node:18
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    command: ["node", "index.js"]
    ports:
      - "3000:3000"

  redis:
    image: registry.registry.svc.cluster.local:5000/redis:7
    ports:
      - "6379:6379"